version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - '*'
      security:
        applies-to: security-updates
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - '*'
