#@data/values-schema
---
#@schema/title "Username"
#@schema/desc "Required string value."
#@schema/validation min_len=1
username: ""
#@schema/title "Replica amount"
#@schema/desc "Required integer value."
#@schema/validation min=1
replicas: 0
#@schema/title "Response Types"
#@schema/desc "Required string array."
#@schema/validation min_len=1
responseTypes:
  - ""
#@schema/title "Credentials"
#@schema/desc "Required map.<br/><strong><em>Click link to see map definition.</em></strong>"
#@schema/nullable
#@schema/validation not_null=True
credential:
  #@schema/title "Credential Name"
  #@schema/desc "Credential name value."
  #@schema/validation min_len=1
  name: ""
  #@schema/title "Cloud Credential"
  #@schema/desc "Credential key value."
  #@schema/validation min_len=1
  cloud: ""
#@schema/title "Password"
#@schema/desc "Ensure exact string length."
#@schema/validation min_len=8, max_len=8
password: ""
#@schema/title "Port Number"
#@schema/desc "Ensure a value between min and max."
#@schema/validation min=1, max=65535
port: 1024
#@schema/title "Cloud Provider"
#@schema/desc "Enumeration of string values."
#@schema/validation one_of=["aws", "azure", "vsphere"]
provider: ""
#@schema/title "Auth Configuration"
#@schema/desc "Exactly one sub property is specified."
#@schema/validation one_not_null=["oidc", "ldap"]
config:
  #@schema/title "OpenID Connect Protocol"
  #@schema/desc "Only <strong>\"oidc\"</strong> or <strong>\"ldap\"</strong> can be specified!"
  #@schema/nullable
  oidc:
    #@schema/title "Client ID"
    #@schema/desc "OIDC Client ID."
    client_id: ""
  #@schema/title "Lightweight Directory Access Protocol"
  #@schema/desc "Only <strong>\"oidc\"</strong> or <strong>\"ldap\"</strong> can be specified!"
  #@schema/nullable
  ldap:
    #@schema/title "Hostname"
    #@schema/desc "LDAP hostname."
    host: ""
#@schema/title "LoadBalancer Selector"
#@schema/desc "Conditional validations can be described manually.<br/><strong><span class=\"text-red-600\">Required:</span> when \"type\" equals \"LoadBalancer\"</strong>"
#@schema/validation min_len=1, when=lambda _, ctx: ctx.parent["type"] == "LoadBalancer"
selector: ""
