name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21

      - uses: carvel-dev/setup-action@v2
        with:
          only: ytt
          ytt: v0.55.2
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm ci
      - run: npm run lint
      - run: npm run build
